//Moves
export const MOVE_SUCCESS = "MOVE_SUCCESS";
export const MOVE_FAIL = "MOVE_FAIL";

//Init
export const CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS";
export const CREATE_GAME_FAIL = "CREATE_GAME_FAIL";
export const JOIN_GAME_SUCCESS = "JOIN_GAME_SUCCESS";
export const JOIN_GAME_FAIL = "JOIN_GAME_FAIL";
export const CONNECT_SOCKET_SUCCESS = "CONNECT_SOCKET_SUCCESS";
export const CONNECT_SOCKET_FAIL = "CONNECT_SOCKET_FAIL";
export const CONNECTING_SOCKET = "CONNECTING_SOCKET";
export const FINISHED_CONNECTING_SOCKET = "FINISHED_CONNECTING_SOCKET";
